name: Generate Summary

on:
  pull_request

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    name: Generate Summary
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          # Checkout pull request HEAD commit instead of merge commit
          ref: ${{ github.event.pull_request.head.sha }}
          # needed for summary to work?
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Print ref
        run: |
          echo base_ref: ${{ github.base_ref }}
          echo head_ref: ${{ github.head_ref }}
          echo ref: ${{ github.ref }}
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate Summary
        run: |
          python3 src/actions/generate-summary.py --base_ref ${{ github.event.pull_request.base.sha }} --head_ref ${{ github.event.pull_request.head.sha }}
      - id: get-comment-body
        run: |
          body=$(cat summary.md)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body
      - name: Create comment
        uses: cccntu/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}